server {
    listen 80;

    # API 요청은 백엔드(Spring Boot)로 프록시
    location /api/ {
            proxy_pass http://backend:8080;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
    }

    # WebSocket 요청 프록시
    location /ws/ {
            proxy_pass http://backend:8080;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 나머지
    location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri /index.html;
    }
}