spring:
  profiles:
    active: dev

  application:
    name: discodeit
  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량

discodeit:
  storage:
    type: local
    local:
      root-path: .discodeit/storage

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: ''

info:
  app:
    name: Discodeit
    app-version: 1.7.0
    java-version: 17
    spring-boot-version: 3.4.0
    main configuration infomation:
      data-source: url, 드라이버 클래스 이름
      jpa: ddl-auto
      storage setting: type, path
      multipart setting: max-file-size, max-request-size