spring:
  config:
    activate:
      on-profiles: prod

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    #        default_batch_fetch_size: 100
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: ERROR

server:
  port: 80