spring:
  config:
    activate:
      on-profiles: test

  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL # postgreSQL과 호환
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG