spring:
  profiles:
    active: dev

  application:
    name: discodeit
  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량

discodeit:
  storage:
    type: local
    local:
      root-path: .discodeit/storage