name: CI Workflow   # 워크플로우 이름 (GitHub Actions 탭에서 표시되는 이름)

on:                 # 워크플로우 실행 조건(트리거 이벤트) 정의
  push:             # pull_request 이벤트 발생 시 실행 -> 나중에 pull_request로 변경해야 함!!!!!!!!!!!!!
    branches: [ "sprint8" ]   # main 브랜치에 pull_request될 때만 실행

jobs:               # 실행할 작업(job)들을 정의
  build:            # "build"라는 이름의 job
    runs-on: ubuntu-latest   # 실행 환경: GitHub이 제공하는 Ubuntu 최신 버전 가상 머신

    steps:          # job 안에서 실행할 단계(step)들
      - uses: actions/checkout@v3   # 현재 리포지토리의 소스 코드를 체크아웃 (가져오기)

      - name: JDK 17 설정
        uses: actions/setup-java@v1   # Java 환경을 세팅하는 공식 액션
        with:
          java-version: '17'          # 설치할 Java 버전 (여기서는 JDK 17)

      - name: 빌드 및 테스트
        run: ./gradlew clean build    # Gradle 빌드 및 테스트 실행 (clean 후 build)

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./build/reports/jacoco/test/jacocoTestReport.xml # codecov가 시각화 할 수 있는 report 파일 의미, 프로젝트 빌드와 테스트 수행 시 gradle build 결과물 내에서 확인